# Generated by Django 4.2.2 on 2023-12-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0003_remove_tenant_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='leased_property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmsapp.property'),
        ),
    ]
