# Generated by Django 4.2.2 on 2023-12-05 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0004_tenant_leased_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lease_end_date',
            field=models.DateTimeField(default='2023-01-01T00:00:00Z'),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_start_date',
            field=models.DateTimeField(default='2023-01-01T00:00:00Z'),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsapp.landlord')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsapp.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rmsapp.tenant')),
            ],
            options={
                'verbose_name_plural': 'Revenues',
            },
        ),
    ]
